# Generated by Django 2.2.5 on 2020-03-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200314_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('common', 'Общий'), ('hidden', 'Скрытый'), ('private', 'Приватный')], default='common', max_length=128, verbose_name='Доступ'),
        ),
    ]
