# Generated by Django 2.2.5 on 2020-03-14 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0003_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessed_to', to='webapp.File', verbose_name='Доступ к файлу')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessed_files', to=settings.AUTH_USER_MODEL, verbose_name='Доступ к пользователю')),
            ],
        ),
    ]
